databases:
  - name: ericblogspot-db
    plan: free

services:
  - type: web
    name: ericblogspot
    plan: free
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: postgresql://ericblogspot_db_user:WlGIQZOdBlOVGt5Bln1k1ipqAQlGmPa4@dpg-d9kk8hdg1s2s73f501qg-a/ericblogspot_db
        fromDatabase:
          name: ericblogspot-db
          property: connectionString
      - key: e825ad62dae39443340ecfb12a51364d
        generateValue: true
      - key: DEBUG
        value: false
