# Generated by Django 6.0.7 on 2026-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('Forex', 'Forex'), ('Cybersecurity', 'Cybersecurity'), ('Emergency', 'Emergency')], max_length=20),
        ),
    ]
