# Generated by Django 6.0.7 on 2026-07-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_is_emergency_alter_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('whatsapp', models.CharField(help_text='e.g. +1234567890', max_length=20)),
                ('telegram', models.URLField(help_text='https://t.me/username')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
